### ISSUE TITLE
'react-native-ios-utilities/RNIRegistrableView.h' file not found

### ISSUE THREAD

**Issue by coolsoftwaretyler** [dominicstop/react-native-ios-utilities#10]
Hey folks,

I'm trying to use this library with [Zeego](https://zeego.dev/start) in an existing React Native Storybook app, built with Expo SDK 51

When I run Expo prebuild and attempt to build my app, I encounter this build error:

```
❌  (node_modules/react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseView.h:9:9)

   7 | 
   8 | #import <UIKit/UIKit.h>
>  9 | #import "react-native-ios-utilities/RNIRegistrableView.h"
     |         ^ 'react-native-ios-utilities/RNIRegistrableView.h' file not found
  10 | #import "react-native-ios-utilities/RNIViewCommandRequestHandling.h"
  11 | #import "react-native-ios-utilities/RNIContentViewParentDelegate.h"
  12 | 
```

Unfortunately I can't get a reproducer app, so I understand if you prefer to close this. It works when I try a fresh Expo installation for both SDK 51 and 52.

I'm hoping that maybe someone has seen this before and knows a quick fix. Thanks in advance for any thoughts!

**Comment by coolsoftwaretyler** [comment]
Ok, I found one difference between my working apps and broken app.

In working apps, `react_native_ios_utilities-Swift.h` seems to be generated. But in the broken app, it isn't. So maybe `use_frameworks!` isn't generating the Swift headers it needs to?

**Comment by dmitry-blackwave** [comment]
Disabling `use_frameworks!` helped me and now xcode can see proper header patches

**Comment by coolsoftwaretyler** [comment]
Hey that worked! Thank you!

**Comment by coolsoftwaretyler** [comment]
So I'm gonna reopen this because while disabling `use_frameworks!` fixed my issue, I still believe it's a problem, and I can reproduce it with the example app in this repository.

## Reproduction steps

1. Clone this repository on `master` branch
2. `yarn install`
3. `cd example && cd ios && USE_FRAMEWORKS="static" pod install`
4. You'll see `USE_FRAMEWORKS="static" pod install` at the top
5. Open up the project in Xcode with `open IosUtilitiesExample.xcworkspace`
6. Build the project, and get this failure: `react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseView.h:9:9 'react-native-ios-utilities/RNIRegistrableView.h' file not found`
7. Try it with dynamic frameworks as well:
8. From the `ios` folder: `pod deintegrate && rm Podfile.lock`
9. `USE_FRAMEWORKS="dynamic" pod install`
10. This tim, you should see `Configuring Pod with dynamically linked Frameworks`
11. Open up the Xcode project again with `open IosUtilitiesExample.xcworkspace`
12. Build the project
13. Same error.

I'm guessing it probably just needs some additional header search paths, I'll investigate to see if I can put together a PR.

**Comment by coolsoftwaretyler** [comment]
Ok, so I've made a little bit of progress. I can get past the missing header errors with this patch:

```patch
diff --git a/ios/Sources/RNIBaseView/RNIBaseView.h b/ios/Sources/RNIBaseView/RNIBaseView.h
index 00a1844..2cc34fd 100644
--- a/ios/Sources/RNIBaseView/RNIBaseView.h
+++ b/ios/Sources/RNIBaseView/RNIBaseView.h
@@ -6,9 +6,16 @@
 //
 
 #import <UIKit/UIKit.h>
-#import "react-native-ios-utilities/RNIRegistrableView.h"
-#import "react-native-ios-utilities/RNIViewCommandRequestHandling.h"
-#import "react-native-ios-utilities/RNIContentViewParentDelegate.h"
+
+#if __has_include(<react_native_ios_utilities/RNIRegistrableView.h>)
+#import <react_native_ios_utilities/RNIRegistrableView.h>
+#import <react_native_ios_utilities/RNIViewCommandRequestHandling.h>
+#import <react_native_ios_utilities/RNIContentViewParentDelegate.h>
+#else
+#import "RNIRegistrableView.h"
+#import "RNIViewCommandRequestHandling.h"
+#import "RNIContentViewParentDelegate.h"
+#endif
 
 #if RCT_NEW_ARCH_ENABLED
 #import <React/RCTViewComponentView.h>
```

But making that change across the codebase seems incorrect. I feel like this is something the umbrella headers should be taking care of. But when I look at the generated umbrella header, it doesn't seem to be able to actually resolve any of the header files.

Another strange thing is that the hyphens on the library name are getting changed to underscores. [I think this happens automatically when Xcode tries to generate the bridging header](https://stackoverflow.com/a/26012612). So maybe the module name being `react-native-ios-utilities` is causing problems with the file paths.

**Comment by coolsoftwaretyler** [comment]
Oh yup, you can make that diff even cleaner. This fixes it when `USE_FRAMEWORKS="dynamic" pod install`:

```
#import "react_native_ios_utilities/RNIRegistrableView.h"
#import "react_native_ios_utilities/RNIViewCommandRequestHandling.h"
#import "react_native_ios_utilities/RNIContentViewParentDelegate.h"
```

I think the main issue might just be name of this module and how it gets transformed by Xcode for bridging headers.

**Comment by anhquan291** [comment]
Hi @coolsoftwaretyler, I hope you're doing well! Since Firebase requires USE_FRAMEWORKS="static", do you have any suggestions ? Appreciate it. Thanks in advance!

**Comment by coolsoftwaretyler** [comment]
I'm working on a PR that will help. I think it's as simple as rewriting the header paths when use_frameworks is used. I don't have it totally done yet but hoping to submit to the repo this weekend.

If you're stuck, you could try patching the way I posted with patch package.

Sorry I don't have a better answer at the moment. Hopefully it'll be sorted out soon.

**Comment by anhquan291** [comment]
> I'm working on a PR that will help. I think it's as simple as rewriting the header paths when use_frameworks is used. I don't have it totally done yet but hoping to submit to the repo this weekend.
> 
> If you're stuck, you could try patching the way I posted with patch package.
> 
> Sorry I don't have a better answer at the moment. Hopefully it'll be sorted out soon.

Take your time. Appreciate it man!

**Comment by coolsoftwaretyler** [comment]
I figured out some of the initial roadblocks, but got stuck on a new problem that I'm having a hard time solving. Pushed my progress up in this PR: https://github.com/dominicstop/react-native-ios-utilities/pull/11

**Comment by coolsoftwaretyler** [comment]
@anhquan291 - my PR in #11 is working for static frameworks now, so while you wait on it to become available, you could fork and patch from that if you need to run Firebase with static frameworks.

**Comment by anhquan291** [comment]
> @anhquan291 - my PR in #11 is working for static frameworks now, so while you wait on it to become available, you could fork and patch from that if you need to run Firebase with static frameworks.

Excellent! I'll try and let you know. Thank you so much.
