### ISSUE TITLE
Dependency on ExpoModulesCore makes it unusable in Bare RN project

### ISSUE THREAD

**Issue by pranshuchittora** [dominicstop/react-native-ios-utilities#4]
Thanks for building a great lib, but looks like it explicitly uses ExpoModulesCore which is not available in bare RN project.

<img width="1512" alt="Screenshot 2024-07-20 at 18 13 29" src="https://github.com/user-attachments/assets/45c3461d-13d9-46f5-aba5-bd1ec88d7f9c">

Other mentions of this issue https://github.com/nandorojo/zeego/issues/77

**Comment by dnk22** [comment]
Has anyone fixed that? Is the error still present in my project?

**Comment by esmailbenmoussa** [comment]
I'm also facing this issue.

**Comment by coolsoftwaretyler** [comment]
I think if you use the `@next` version, this limitation is gone.

Notice the example app on master doesn't use Expo. I was able to spin it up in a RN CLI project for a recent PR as well.

**Comment by pranshuchittora** [comment]
I can confirm that using the `@next` version (v5) happens to fix this issue.

**Comment by pranshuchittora** [comment]
I can confirm that using the `@next` version (v5) happens to fix this issue.
