### ISSUE TITLE
Sentry reporting app hangs greater than 2000ms during RNIUtilitiesManager.init

### ISSUE THREAD

**Issue by kimdanielarthur-cowlabs** [dominicstop/react-native-ios-utilities#5]
Not sure if its something specific to our overall app initialisation or if its specific to the library, however thought it would be good to share incase there is something in this library. Occurs across a wide selection of ios devices

believe the library is used through zeego for native dropdown components

expo: 51.0.12
react-native-ios-utilities: 4.4.5
zeego: 1.10.0

```
libswiftCore        0x187b5d964  const::lambda::operator()
  libswiftCore        0x187b5c7b8  swift_conformsToProtocolMaybeInstantiateSuperclasses
  libswiftCore        0x187b5ab44  swift_conformsToProtocolCommon
  libswiftCore        0x187afe9ec  swift::_conformsToProtocol
  libswiftCore        0x187b06be0  _conformsToProtocols
  libswiftCore        0x187b06680  tryCastToExistentialMetatype
  libswiftCore        0x187b04064  tryCast
  libswiftCore        0x187b04408  tryCast
  libswiftCore        0x187b03b10  swift_dynamicCast
  OurApp              0x1026630ec  closure in Array<T>.getClasses<T> (Array+AnyClass.swift:48)
  OurApp              0x102662ff0  _ArrayProtocol.filter (<compiler-generated>)
  OurApp              0x102662ff0  Array<T>.getClasses<T> (Array+AnyClass.swift:48)
  OurApp              0x102cd9ad8  RNIUtilitiesManager.init (RNIUtilitiesManager.swift:24)
  OurApp              0x102cd9850  RNIUtilitiesManager.__allocating_init (RNIUtilitiesManager.swift)
  OurApp              0x102cd9850  shared (RNIUtilitiesManager.swift:15)
  libdispatch         0x190d65dd0  _dispatch_client_callout
  libdispatch         0x190d67650  _dispatch_once_callout
  OurApp              0x102cd97a8  RNIUtilitiesManager.shared.unsafeMutableAddressor (RNIUtilitiesManager.swift:15)
  OurApp              0x102cd97a8  RNIUtilitiesManagerShared (RNIUtilitiesManager.swift:11)
  libdispatch         0x190d65dd0  _dispatch_client_callout
  libdispatch         0x190d67650  _dispatch_once_callout
  OurApp              0x102cda218  RNIUtilitiesManagerShared.unsafeMutableAddressor (RNIUtilitiesManager.swift:11)
  OurApp              0x102cda218  closure in RNIUtilitiesModule.definition (RNIUtiltiesModule.swift:26)
  OurApp              0x10254ef94  thunk for closure (<compiler-generated>)
  libdispatch         0x190d64138  _dispatch_call_block_and_release
  libdispatch         0x190d65dd0  _dispatch_client_callout
  libdispatch         0x190d745a0  _dispatch_main_queue_drain
  libdispatch         0x190d741b4  _dispatch_main_queue_callback_4CF
  CoreFoundation      0x188e9370c  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x188e90910  __CFRunLoopRun
  CoreFoundation      0x188e8fcd4  CFRunLoopRunSpecific
  GraphicsServices    0x1cdd401a4  GSEventRunModal
  UIKitCore           0x18b4c8908  -[UIApplication _run]
  UIKitCore           0x18b57c9cc  UIApplicationMain
  OurApp              0x1024fc408  main (main.m:7)
```

**Comment by dominicstop** [comment]
hello, thank you for the detailed response; i am currently investigating the issue

**Comment by dominicstop** [comment]
hello, thank you for your patience—i've releases a couple of fixes (i really hope i didn't break anything, as i'm currently unable to test the changes due to the in-progress rewrite in [wip-new-arch](https://github.com/dominicstop/react-native-ios-utilities/tree/wip-new-arch) branch)
<br>
**Changes**:
* `react-native-ios-utilities` ([v4.5.0](https://github.com/dominicstop/react-native-ios-utilities/releases/tag/v4.5.0) | [changes](https://github.com/dominicstop/react-native-ios-utilities/compare/v4.4.6-4...v4.5.0))
* `DGSwiftUtilities` (0.27.0 | [changes](https://github.com/dominicstop/DGSwiftUtilities/compare/0.26.0...0.27.0))
<br>
if there's still something wrong, please reopen this issue, and tag me so i get notified

**Comment by cxp723** [comment]
currently I get crashes that look very similar to this one:

Crashed: com.apple.root.user-initiated-qos
0  libswiftCore.dylib             0x32a6e8 getContextDescriptor(swift::TargetMetadata<swift::InProcess> const*) + 20
1  libswiftCore.dylib             0x32a86c swift_conformsToProtocolMaybeInstantiateSuperclasses(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, bool) + 128
2  libswiftCore.dylib             0x32a58c swift_conformsToProtocol + 100
3  libswiftCore.dylib             0x2ea790 swift::_conformsToProtocol(swift::OpaqueValue const*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptorRef<swift::InProcess>, swift::TargetWitnessTable<swift::InProcess> const**) + 44
4  libswiftCore.dylib             0x2f0c00 _conformsToProtocols(swift::OpaqueValue const*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetExistentialTypeMetadata<swift::InProcess> const*, swift::TargetWitnessTable<swift::InProcess> const**) + 156
5  libswiftCore.dylib             0x2f087c tryCastToExistentialMetatype(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 304
6  libswiftCore.dylib             0x2ee9fc tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 648
7  libswiftCore.dylib             0x2eecd8 tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 1380
8  libswiftCore.dylib             0x2ee640 swift_dynamicCast + 172
**9  MyApp                   0x6c718 closure #1 in Array<A>.getClasses<A>(ofType:) + 48 (Array+AnyClass.swift:48)
10 MyApp                   0x6c618 Array<A>.getClasses<A>(ofType:) + 47 (Array+AnyClass.swift:47)
11 MyApp                   0x6871d4 closure #1 in RNIUtilitiesManager._setupRegisterDelegates(withClasses:) + 58 (RNIUtilitiesManager.swift:58)
12 MyApp                   0x829b4 thunk for @escaping @callee_guaranteed @Sendable () -> () + 4334660020 (<compiler-generated>:4334660020)**
13 libdispatch.dylib              0x637a8 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x64780 _dispatch_client_callout + 16
15 libdispatch.dylib              0x48d88 _dispatch_root_queue_drain + 616
16 libdispatch.dylib              0x49430 _dispatch_worker_thread2 + 160
17 libsystem_pthread.dylib        0x1b94 _pthread_wqthread + 224
18 libsystem_pthread.dylib        0x1720 start_wqthread + 8

I'm using:
"react-native-ios-context-menu": "2.5.1",
"react-native-ios-utilities": "4.5.1",
